return {
  expandtab      = true, -- Converts tabs to spaces
  smartindent    = true, -- Makes indenting smart
  wrap           = false, -- Display long lines as just one line
  cursorline     = true, -- Enable highlighting of the current line
  signcolumn     = "no", -- Always show the signcolumn, otherwise it would shift the text each time
  colorcolumn    = "9999", -- fixes indentline for now
  conceallevel   = 0, -- so that `` is visible in markdown files
  number         = true, -- set numbered lines
  relativenumber = true, -- set relative number
  numberwidth    = 2, -- set number column width to 2 {default 4}
  cpt            = ".,k,w,b",
  completeopt    = "menu,menuone,noinsert",
  hidden         = true, -- Required to keep multiple buffers open multiple buffers
  backup         = false, -- This is recommended by coc
  backupcopy     = "yes", -- When dave files, do not change file name.
  writebackup    = false, -- This is recommended by coc
  swapfile       = false,
  undofile       = true,  -- Enable persistent undo
  undodir        = vim.fn.stdpath('data') ..'/.undo',
  previewheight  = 8,
  scrolloff      = 1,
  sidescrolloff  = 8,
  tabstop        = 4,
  shiftwidth     = 4,
  softtabstop    = -1,
  mouse          = "a", -- Enable your mouse
  selectmode     = "key",
  clipboard      = "unnamedplus", -- Copy paste between vim and everything else
  updatetime     = 300, -- Faster completion
  updatecount    = 100,
  laststatus     = 3,
  showtabline    = 0, -- Never show tabs
  showcmd        = true,
  showmode       = false,
  cmdheight      = 0, -- More space for displaying messages can set to 1
  ruler          = true,
  magic          = true,
  foldenable     = true,
  foldmethod     = "indent",
  foldcolumn     = "0",
  foldlevel      = 1,
  foldlevelstart = 99,
  confirm        = true,
  backspace      = "indent,eol,start",
  gdefault       = true,
  timeout        = true,
  timeoutlen     = 300, -- By default timeoutlen is 1000 ms
  ttimeoutlen    = 0,  -- By default timeoutlen is 1000 ms
  showmatch      = true, -- highlight the matching quota
  matchtime      = 1,
  ignorecase     = true,
  hlsearch       = true,
  incsearch      = true,
  smartcase      = true,
  encoding       = "utf-8",
  fileencoding   = "utf-8", -- The encoding written to file
  wildmenu       = true,
  autowrite      = true,
  splitbelow     = true, -- Horizontal splits will automatically be below
  splitright     = true, -- Vertical splits will automatically be to the right
  splitkeep      = "screen", -- cursor, screen, topline
  title          = true,
  pumheight      = 10, -- Makes popup menu smaller
  syntax         = "on",  -- syntax highlighting
  termguicolors  = true, -- set term gui colors most terminals support this
  guifont        = "Consolas:h14",
  -- background     = "dark",
  background     = "light",
  lazyredraw     = true, -- do not render UI when run macro
  -- statuscolumn   = "%=%{v:relnum?v:relnum:v:lnum} ",
  listchars      = { trail = "␣", nbsp = "⍽", tab = "⇥ ", }, -- leadmultispace = "┊ ",tab = "⇥ ", eol = '↵',
  list           = false, -- when set this, the cursor will missing
}
